spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: equipos-route
          uri: lb://equipo                        # <– cambia aquí
          predicates:
            - Path=/equipos/**
          filters:
            - StripPrefix=1

        - id: entrenadores-route
          uri: lb://entrenadores                  # <– y aquí
          predicates:
            - Path=/entrenadores/**
          filters:
            - StripPrefix=1

        - id: miembros-route
          uri: lb://miembros                      # <– y aquí
          predicates:
            - Path=/miembros/**
          filters:
            - RewritePath=/miembros/(?<remaining>.*), /api/miembro/${remaining}

        - id: clase-route
          uri: lb://clase                         # <– y aquí
          predicates:
            - Path=/clase/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
